{% set name = "ruby-enum" %}
{% set version = "0.8.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: dcf27c6dc5ea040fd8d5fd14a7dadf201ca718c2c3f296d436ed07f245f76d34

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-i18n >=0

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: Enum-like behavior for Ruby.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/dblock/{{ name }}

extra:
  recipe-maintainers:
    - sodre
