travis:
  secure:
    BINSTAR_TOKEN: fOd482Cc8VT4cIuI05zmf/ooa5D4CCAdpMEJZ2Ua3TU9hMRBmkv/GtsJBo/7e7uZBmaUn4WzdPKyqk5Tmxwccc7+0J6EpAunXAdi3BiNCJAf4tSeDhLqMSOap4l0pLPzcEB1orx4MKzJv3bVUqvqMb0gxBDrtDHgZhNMo5quQRWuVJ+HFrL4NQXmaeUstZN/9EFONEOkGJiuqmOmdhexNI2CVr6uhTd8wKoC16R/0v8JZUpT0L0KNV9YRP+GOmi3JBZzmGo40k/Rs44wJtJzoOiBu+pfXAmS89RBVFoscvavLJhT+rFjq8qJmQ1hiF/gM/M7IfitFuwLjvFn9Q2HmB1sIap9HpzMMPFm+XwXen+mjRHM9d7f7DMC8IYKq+6alnnjiJiqoPa2mpwxjn6he9EblWQMkhQHFyrmwWsuQLBl++lGQcjUJRKvwRUOxWXXSuZVIO11oB2otBGdmrNvR0Tgzd+wrvTfvTxDVgazkh/x1vXKfqBS81FIoPHX2U1PCf43yD1XNxp+sC56ErAp/UMb49++ToK8KtlI1LIO/ld5OjRSFC6VktpZldno57CpZzvZv7V9ZVRBT9aLVxuM5I9ln3gtNH7REpeyI+Ib1va1grnMBzEK4pk067Vb+Byqh2zXUa+q/s1v0txtY9lHEULp8hSyqJvg75MgGDMrMw4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
